import { PRODUCTS } from "../../../constants/products";
import { expect, test } from "../../../fixtures";

test("inventory page loads correctly", async ({ inventoryPage }) => {
  await expect(inventoryPage.title).toHaveText("Products");
});

test("should add a product to cart successfully", async ({
  inventoryPageWithItem,
}) => {
  await expect(inventoryPageWithItem.cartBadge).toHaveText("1");
});

test("should remove a product from cart successfully", async ({
  inventoryPageWithItem,
}) => {
  await expect(inventoryPageWithItem.cartBadge).toHaveText("1");
  await inventoryPageWithItem.removeProductFromCart(PRODUCTS.BIKE_LIGHT);
  await expect(inventoryPageWithItem.cartBadge).toHaveCount(0);
});

test("should navigate to cart page when clicking on cart icon", async ({
  inventoryPage,
}) => {
  const cartPage = await inventoryPage.goToCart();
  await expect(cartPage.title).toHaveText("Your Cart");
});

test("inventory page loads within performance budget", async ({
  // inventoryPage fixture navigates to /inventory.html before the test body runs.
  // It reads PerformanceNavigationTiming entry generated by that navigation,
  // rather than measuring navigation duration directly in the test.
  inventoryPage,
}) => {
  const timing = await inventoryPage.page.evaluate(() => {
    const nav = performance.getEntriesByType(
      "navigation",
    )[0] as PerformanceNavigationTiming;

    return {
      domContentLoaded: nav.domContentLoadedEventEnd - nav.startTime,
      loadEvent: nav.loadEventEnd - nav.startTime,
      ttfb: nav.responseStart - nav.requestStart,
    };
  });

  expect(
    timing.ttfb,
    `TTFB ${timing.ttfb.toFixed(0)} ms exceeded 300 ms budget`,
  ).toBeLessThan(300);

  expect(
    timing.domContentLoaded,
    `DCL ${timing.domContentLoaded.toFixed(0)} ms exceeded 1 500 ms budget`,
  ).toBeLessThan(1500);

  expect(
    timing.loadEvent,
    `Load ${timing.loadEvent.toFixed(0)} ms exceeded 2 500 ms budget`,
  ).toBeLessThan(2500);
});

test("all critical assets load successfully", async ({ page }) => {
  const failed: string[] = [];

  page.on("response", (response) => {
    const type = response.request().resourceType();

    if (
      ["stylesheet", "script", "image", "font"].includes(type) &&
      response.status() >= 400
    ) {
      failed.push(`${response.status()} ${response.url()}`);
    }
  });

  await page.goto("/inventory.html");

  expect(failed, `Failed assets:\n${failed.join("\n")}`).toEqual([]);
});

test("LCP is within the Core Web Vitals good threshold", async ({
  inventoryPage,
}) => {
  const lcp = await inventoryPage.page.evaluate(() => {
    return new Promise<number>((resolve) => {
      new PerformanceObserver((list) => {
        const entries = list.getEntries();
        if (entries.length > 0) {
          resolve(entries[entries.length - 1].startTime);
        }
      }).observe({ type: "largest-contentful-paint", buffered: true });

      setTimeout(() => resolve(Infinity), 5000);
    });
  });

  expect(
    lcp,
    `LCP ${lcp.toFixed(0)} ms exceeded the 2 000 ms budget`,
  ).toBeLessThan(2000);
});
